### ISSUE TITLE
Function to get data about mods installed in folder

### ISSUE THREAD

**Issue by Danielv123** [Danacus/node-factorio-api#1]
Should either take a folder or use the folder specified when initializing. Should return an array of all the mods in that folder with their name and version.

**Comment by Danacus** [comment]
Is this a feature request, a bug or something you want be to change. I'm a little confused.

**Comment by Danielv123** [comment]
This is a feature request. Currently you can only batch extract mod info from a savefile.

**Comment by Danacus** [comment]
I will probably add this tomorrow. You can use loadInstalledMods(), but it's probably too slow for what you want, because it reads all information about every single mod by opening the zip files. I'll add a simple function to get the name and version from every mod in a folder from the file name.

**Comment by Danacus** [comment]
Added in 5bf08a3950883cd207c05f23eb493587cc350755

**Comment by Danacus** [comment]
I didn't do a lot of testing, but it should be working.

**Comment by Danielv123** [comment]
Works very well, thanks :)
