### ISSUE TITLE
Seems to download the oldest version of mod available

### ISSUE THREAD

**Issue by Danielv123** [Danacus/node-factorio-api#8]
```
factorioAPI.searchMods("clusterio").then(body => {
	console.log("Im gonna download: "+body[0].name);
	factorioAPI.downloadMod(body[0]).then(()=>{
		console.log("Mod downloaded");
	});
});
```

This downloads the oldest version of clusterio available, from 0.14. Does not sound like intended behaviour.

**Comment by Danacus** [comment]
After taking a quick look I noticed that they decided to invert the order of the releases. I will fix this very soon.

**Comment by Danielv123** [comment]
Heh, thats a weird thing to do on their behalf.

**Comment by Danacus** [comment]
It is, no idea why they would do that

**Comment by Danacus** [comment]
Fixed in 2393410562cb64c3439c9feca634b59f18b643ba

**Comment by Danacus** [comment]
Oh, and btw, you can just use this:

```
factorioAPI.downloadMod({name: 'clusterio'}).then(()=>{
	console.log("Mod downloaded");
});
```

So you don't have to search for the mod.

**Comment by Danielv123** [comment]
The search is to allow me to use partial mod names, thanks for fixing 👍
